package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'testautogithubApp'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("testautogithubApp")) {
    val expected = GitVcsRoot({
        id("testautogithubApp")
        name = "githubApptoken"
        url = "https://github.com/TomSunGit/test-auto.git"
        branch = "refs/heads/main"
        authMethod = token {
            userName = "oauth2"
            tokenId = "c_token_id:CID_2c5b3636664801e1f78a3949495cffc1:-1:de5e6c52-d840-4f0f-b045-f0cf062627ec"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_2c5b3636664801e1f78a3949495cffc1:-1:07e5a94d-1bf0-4087-b95c-e17af8761364"
        }
    }

}
